-- Seed common ingredients for autocomplete
-- Use INSERT ... ON CONFLICT DO NOTHING for idempotency

-- Produce
INSERT INTO ingredients (name) VALUES
  ('onion'),
  ('garlic'),
  ('tomato'),
  ('potato'),
  ('carrot'),
  ('celery'),
  ('bell pepper'),
  ('broccoli'),
  ('spinach'),
  ('lettuce'),
  ('cucumber'),
  ('mushroom'),
  ('zucchini'),
  ('lemon'),
  ('lime'),
  ('ginger'),
  ('green onion'),
  ('jalapeño'),
  ('avocado'),
  ('corn'),
  ('asparagus'),
  ('cabbage'),
  ('kale'),
  ('cauliflower'),
  ('sweet potato'),
  ('eggplant'),
  ('green beans'),
  ('peas'),
  ('cilantro'),
  ('parsley'),
  ('basil (fresh)'),
  ('mint'),
  ('dill')
ON CONFLICT (name) DO NOTHING;

-- Proteins
INSERT INTO ingredients (name) VALUES
  ('chicken breast'),
  ('chicken thigh'),
  ('ground beef'),
  ('ground turkey'),
  ('salmon'),
  ('shrimp'),
  ('tofu'),
  ('bacon'),
  ('sausage'),
  ('pork chop'),
  ('pork tenderloin'),
  ('ground pork'),
  ('steak'),
  ('beef roast'),
  ('lamb'),
  ('cod'),
  ('tilapia'),
  ('tuna'),
  ('crab'),
  ('lobster'),
  ('scallops'),
  ('mussels'),
  ('turkey breast'),
  ('duck'),
  ('ham'),
  ('tempeh'),
  ('seitan')
ON CONFLICT (name) DO NOTHING;

-- Dairy & Eggs
INSERT INTO ingredients (name) VALUES
  ('butter'),
  ('milk'),
  ('heavy cream'),
  ('sour cream'),
  ('cream cheese'),
  ('cheddar cheese'),
  ('parmesan cheese'),
  ('mozzarella cheese'),
  ('eggs'),
  ('yogurt'),
  ('greek yogurt'),
  ('feta cheese'),
  ('goat cheese'),
  ('ricotta cheese'),
  ('swiss cheese'),
  ('provolone cheese'),
  ('blue cheese'),
  ('half and half'),
  ('buttermilk'),
  ('cottage cheese'),
  ('mascarpone'),
  ('brie'),
  ('gruyère cheese')
ON CONFLICT (name) DO NOTHING;

-- Pantry Staples
INSERT INTO ingredients (name) VALUES
  ('olive oil'),
  ('vegetable oil'),
  ('flour'),
  ('sugar'),
  ('brown sugar'),
  ('salt'),
  ('black pepper'),
  ('rice'),
  ('pasta'),
  ('bread crumbs'),
  ('chicken broth'),
  ('beef broth'),
  ('vegetable broth'),
  ('soy sauce'),
  ('vinegar'),
  ('honey'),
  ('maple syrup'),
  ('baking powder'),
  ('baking soda'),
  ('vanilla extract'),
  ('cornstarch'),
  ('tomato paste'),
  ('tomato sauce'),
  ('canned tomatoes'),
  ('coconut milk'),
  ('peanut butter'),
  ('almond butter'),
  ('sesame oil'),
  ('fish sauce'),
  ('worcestershire sauce'),
  ('hot sauce'),
  ('mustard'),
  ('dijon mustard'),
  ('mayonnaise'),
  ('ketchup'),
  ('red wine vinegar'),
  ('balsamic vinegar'),
  ('apple cider vinegar'),
  ('rice vinegar'),
  ('white wine'),
  ('red wine'),
  ('lentils'),
  ('black beans'),
  ('kidney beans'),
  ('chickpeas'),
  ('cannellini beans'),
  ('quinoa'),
  ('oats'),
  ('breadcrumbs'),
  ('panko'),
  ('tortillas'),
  ('noodles'),
  ('rice noodles'),
  ('couscous'),
  ('tahini'),
  ('miso paste'),
  ('oyster sauce'),
  ('hoisin sauce'),
  ('coconut oil'),
  ('canola oil'),
  ('peanut oil')
ON CONFLICT (name) DO NOTHING;

-- Spices & Seasonings
INSERT INTO ingredients (name) VALUES
  ('paprika'),
  ('cumin'),
  ('oregano'),
  ('basil (dried)'),
  ('thyme'),
  ('rosemary'),
  ('cinnamon'),
  ('chili powder'),
  ('cayenne pepper'),
  ('garlic powder'),
  ('onion powder'),
  ('italian seasoning'),
  ('curry powder'),
  ('turmeric'),
  ('garam masala'),
  ('coriander'),
  ('nutmeg'),
  ('ginger powder'),
  ('bay leaves'),
  ('red pepper flakes'),
  ('smoked paprika'),
  ('sage'),
  ('tarragon'),
  ('cardamom'),
  ('cloves'),
  ('allspice'),
  ('fennel seeds'),
  ('mustard seeds'),
  ('celery salt'),
  ('white pepper'),
  ('star anise'),
  ('saffron'),
  ('za''atar'),
  ('sumac'),
  ('five spice powder')
ON CONFLICT (name) DO NOTHING;

-- Nuts & Seeds
INSERT INTO ingredients (name) VALUES
  ('almonds'),
  ('walnuts'),
  ('pecans'),
  ('cashews'),
  ('peanuts'),
  ('pine nuts'),
  ('pistachios'),
  ('hazelnuts'),
  ('sunflower seeds'),
  ('pumpkin seeds'),
  ('sesame seeds'),
  ('chia seeds'),
  ('flax seeds'),
  ('macadamia nuts')
ON CONFLICT (name) DO NOTHING;

-- Fruits
INSERT INTO ingredients (name) VALUES
  ('apple'),
  ('banana'),
  ('orange'),
  ('strawberries'),
  ('blueberries'),
  ('raspberries'),
  ('grapes'),
  ('mango'),
  ('pineapple'),
  ('peach'),
  ('pear'),
  ('cherry'),
  ('cranberries'),
  ('raisins'),
  ('dates'),
  ('dried apricots'),
  ('coconut'),
  ('watermelon'),
  ('cantaloupe'),
  ('honeydew'),
  ('kiwi'),
  ('pomegranate'),
  ('fig'),
  ('plum'),
  ('grapefruit')
ON CONFLICT (name) DO NOTHING;
